apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: d7esqich3-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/d7esqich3-java-springboot-gitops